version: "3.7"

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.15
    ports:
      - 1883:1883  # mqtt port
      - 8080:8080  # ws port
    volumes:
      - ./mosquitto/dev.mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/passwordfile:/mosquitto/passwordfile
      - ./mosquitto/docker-entrypoint.sh:/docker-entrypoint.sh
